version: '1'
services:
  node-producer:
    extends:
      file: ./node-producer/docker-compose.yaml
      service: node-producer
    depends_on:
      apache-kafka-broker:
        condition: service_healthy
    networks:
      - kafka

  node-consumer:
    extends:
      file: ./node-consumer/docker-compose.yaml
      service: node-consumer
    depends_on:
      apache-kafka-broker:
        condition: service_healthy
    networks:
      - kafka
  
  apache-kafka-zookeeper:
    extends:
      file: ./apache-kafka/docker-compose.yaml
      service: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD", "nc", "-vz", "apache-kafka-zookeeper", "2181"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - kafka
  
  apache-kafka-broker:
    depends_on:
      apache-kafka-zookeeper:
        condition: service_healthy
    extends:
      file: ./apache-kafka/docker-compose.yaml
      service: kafka
    networks:
      - kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: apache-kafka-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://apache-kafka-broker:9092,PLAINTEXT_HOST://apache-kafka-zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "nc", "-vz", "apache-kafka-broker", "9092"]
      interval: 10s
      timeout: 10s
      retries: 5


networks:
  kafka:
    driver: bridge
